name: Secrets

on:
  workflow_call: {}
  push:
    branches:
      - chore/gh-actions-debug

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  check-secret:
    runs-on: ubuntu-latest
    env:
      ENTITLE_WORKFLOW_ID: ${{ secrets.ENTITLE_WORKFLOW_ID }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - name: Check if ENTITLE_WORKFLOW_ID is set
        run: |
          if [ -z "$ENTITLE_WORKFLOW_ID" ]; then
            echo "❌ ENTITLE_WORKFLOW_ID is NOT set or empty"
            exit 1
          else
            echo "✅ ENTITLE_WORKFLOW_ID is set"
          fi
      - run: go mod download
      - env:
          TF_ACC: "1"
          ENTITLE_API_KEY: ${{ secrets.ENTITLE_API_KEY }}
          ENTITLE_OWNER_EMAIL: ${{ secrets.ENTITLE_OWNER_EMAIL }}
          ENTITLE_OWNER_ID: ${{ secrets.ENTITLE_OWNER_ID }}
          ENTITLE_WORKFLOW_ID: ${{ secrets.ENTITLE_WORKFLOW_ID }}
        run: go test -v -cover ./tmp
        timeout-minutes: 10
